# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            '[quandrei]'
tagline:          'a cipher, wrapped in an enigma, smothered in secret sauce'
description:      'What you are experiencing is a temporary distortion of reality. Do not be alarmed.'
url:              http://quandrei.github.io

author:
  name:           'Andrea Zarbo'
  url:            http://quandrei.github.io

paginate:         3

# Custom vars

github:
  url:            https://github.com/quandrei

linkedin:
  url:            https://www.linkedin.com/in/andreazarbo

twitter:
  url:			  https://twitter.com/quandrei
