# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            quandrei.github.io
tagline:          'a cipher, wrapped in an enigma, smothered in secret sauce'
description:      'What you are experiencing is a temporary distortion of reality. Do not be alarmed.'
url:              http://quandrei.github.io

author:
  name:           'Andrea Zarbo'
  url:            https://twitter.com/quandrei

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/quandrei
